name: React CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: |
            cd fullstack_front
            npm ci
        - name: Build & push Docker image
          uses: actions/checkout@v3
          run: 
           locker login --username sarvagyaagrawal --password ${{ secrets.DOCKER_PASSWORD }} ghcr.io
           docker build . --tag ghcr.io/sarvagyaagrawal/employee:latest
           docker push ghcr.io/sarvagyaagrawal/employee:latest
      
